# Generated by Django 4.2.3 on 2023-08-12 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0006_delete_imagem"),
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="produto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="produto.produto",
            ),
        ),
    ]
