# Generated by Django 4.2.3 on 2023-08-21 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0002_image_produto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="produto",
        ),
    ]
