# Generated by Django 4.2.4 on 2023-09-06 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0003_remove_image_produto"),
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="imagem_perfil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="uploader.image",
            ),
        ),
    ]
