# Generated by Django 4.2.4 on 2023-09-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0002_usuario_imagem_perfil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="imagem_perfil",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
