# Generated by Django 4.2.6 on 2023-10-25 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0003_remove_image_produto"),
        ("usuario", "0003_alter_usuario_imagem_perfil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="imagem_perfil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imagem_perfil",
                to="uploader.image",
            ),
        ),
    ]
