# Generated by Django 4.2.6 on 2023-10-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0007_remove_usuario_imagem_perfil_usuario_imagem_perfil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="imagem_perfil",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
