# Generated by Django 4.2.3 on 2023-08-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0003_alter_imagem_options_produto_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fabricante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.CharField(max_length=255)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="fabricantes/"),
                ),
                ("site", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="produto",
            name="precoPromo",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="promo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="produto",
            name="quantidade",
            field=models.IntegerField(default=0),
        ),
    ]
