# Generated by Django 4.2.3 on 2023-08-09 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0004_fabricante_produto_precopromo_produto_promo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="fabricante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="produto.fabricante",
            ),
        ),
    ]
