# Generated by Django 4.2.3 on 2023-08-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0003_remove_image_produto"),
        ("produto", "0006_delete_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="imagens",
            field=models.ManyToManyField(blank=True, to="uploader.image"),
        ),
    ]
