# Generated by Django 4.2.4 on 2023-09-20 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0003_remove_image_produto"),
        ("produto", "0007_produto_imagens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="thumbnail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thumbnail",
                to="uploader.image",
            ),
        ),
    ]
