# Generated by Django 4.2.4 on 2023-09-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0008_alter_produto_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="produto.categoria"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="fabricante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="produto.fabricante",
            ),
        ),
    ]
