# Generated by Django 4.2.4 on 2023-09-20 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0009_alter_produto_categoria_alter_produto_fabricante"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="produto.categoria",
            ),
        ),
    ]
