# Generated by Django 4.2.4 on 2023-09-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_alter_produto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='fabricante',
        ),
    ]
