# Generated by Django 4.2.4 on 2023-09-26 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_remove_produto_categoria_remove_produto_fabricante'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.categoria'),
        ),
        migrations.AddField(
            model_name='produto',
            name='fabricante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.fabricante'),
        ),
    ]
