# Generated by Django 4.2.4 on 2023-09-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0012_produto_categoria_produto_fabricante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produto.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='fabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produto.fabricante'),
        ),
    ]
