# Generated by Django 4.2.4 on 2023-09-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0015_alter_produto_nome21'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='nome21',
        ),
    ]
