# Generated by Django 4.2.3 on 2023-09-26 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0016_remove_produto_nome21"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fabricante",
            name="logo",
        ),
    ]
